name: "main"

on:
  push:
    branches: ["master"]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

permissions:
  contents: "read"
  pull-requests: "read"

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-go@v5"
        with:
          go-version: "1.25"
      - uses: "actions/cache@v4"
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.25-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.25-
      - run: |
          go mod download
      - run: |
          go mod verify
      - run: |
          make vet
      - run: |
          make test
      - run: |
          make test-fuzz
