name: "main"

on:
  push:
    branches: ["master"]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  test:
    name: "test"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      pull-requests: "read"
      packages: "write"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "sigstore/cosign-installer@v3"
      - uses: "anchore/sbom-action/download-syft@v0"
      - uses: "actions/setup-go@v5"
        with:
          go-version: "1.25"
      - uses: "actions/cache@v4"
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.25-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.25-
      - run: |
          go mod download
      - run: |
          go mod verify
      - run: |
          make vet
      - run: |
          make test
      - run: |
          make test-fuzz
      - uses: "goreleaser/goreleaser-action@v6"
        with:
          distribution: "goreleaser"
          version: "~> v2"
          args: "release --clean --snapshot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
